---
functional:
  - требование 3
  - требование 4
  - требование 8
  - требование 9
non-functional:
  - требование 1
  - требование 2
  - требование 5
  - требование 6
  - требование 10
  - требование 7
implicit:
  - пользователь должен иметь возможность оформлять заказ после того, как добавлены товары в корзину.
  - пользователь должен иметь возможность удалить товар из корзины.
  - на сайте должна быть форма регистрации, в которой пользователь указывает свой номер телефона для связи. 
  - пользователь должен иметь возможность выбрать необходимое количество товара в штуках. 
  - только зарегистрированный пользователь должен иметь возможность добавлять товары в корзину и оформлять заказ.
